version: '3.1'

services:
  db:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cosmic_python_db
    ports:
      - 5433:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/db_volume
