version: '3.1'

services:
  db:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cosmic_python_db
    ports:
      - 5435:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
  flask_api:
    image: flask_api:latest
    build: ./
    environment:
      - DB_PORT=5435
      - DB_HOST=db # this is the way to reference another service's hostname
    ports:
      - 5000:5000
    volumes:
      - ./:/code
    depends_on:
      - "db"

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/persistent_store/db_volume
