"""create customer add foreign key

Revision ID: 1266cd5fd42a
Revises: 786a7744b2fe
Create Date: 2023-11-19 23:56:12.893093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1266cd5fd42a'
down_revision: Union[str, None] = '786a7744b2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('batch', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batch', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'batch', type_='foreignkey')
    op.drop_column('batch', 'customer_id')
    op.drop_table('customer')
    # ### end Alembic commands ###
