"""changed foreign key references

Revision ID: a3c55bc47f7d
Revises: 9364209de6b7
Create Date: 2024-06-19 07:40:10.785532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c55bc47f7d'
down_revision: Union[str, None] = '9364209de6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('orderid', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orderid')
    )
    op.create_table('product',
    sa.Column('sku', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('batch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('_purchased_quantity', sa.Integer(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sku'], ['product.sku'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orderline_id', sa.String(length=255), nullable=True),
    sa.Column('batch_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.reference'], ),
    sa.ForeignKeyConstraint(['orderline_id'], ['order_lines.orderid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocations')
    op.drop_table('batch')
    op.drop_table('product')
    op.drop_table('order_lines')
    # ### end Alembic commands ###
