"""update

Revision ID: e54ce7b74b03
Revises: 1266cd5fd42a
Create Date: 2023-12-01 18:16:40.576115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54ce7b74b03'
down_revision: Union[str, None] = '1266cd5fd42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('some_table')
    op.drop_constraint('batch_customer_id_fkey', 'batch', type_='foreignkey')
    op.drop_column('batch', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('batch_customer_id_fkey', 'batch', 'customer', ['customer_id'], ['id'])
    op.create_table('some_table',
    sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customer_pkey')
    )
    # ### end Alembic commands ###
